

version: '3'

services:
  django:
    build: ./project
    command: sh -c "gunicorn --bind 0.0.0.:8000 app.wsgi"
    expose:
      - 8000
    ports:
      - "8000:8000"
    volumes:
      - ./project/project
      - static_data:/project/static
